// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"supply-chain-mall/controller"
	"supply-chain-mall/pkg/core"
	"supply-chain-mall/svc"
)

// Injectors from wire.go:

func NewInjector() (*core.AppProvider, error) {
	engine := controller.NewGinServer()
	productService := &svc.ProductService{}
	product := &controller.Product{
		ProductSvc: productService,
	}
	controllers := &controller.Controllers{
		Product: product,
	}
	appProvider := &core.AppProvider{
		Engine:      engine,
		Controllers: controllers,
	}
	return appProvider, nil
}
